name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup environment variables
      run: echo "REACT_APP_WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env

    - name: Build project
      run: |
        # Any build steps if needed (e.g., compiling, minifying CSS/JS)
        echo "Building the project"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Adjust this if your build outputs to a different directory
