name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup environment variables
      run: echo "REACT_APP_WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Stash changes
      run: |
        git stash

    - name: Pull latest changes
      run: |
        git remote set-url origin "https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}"
        git pull origin main --rebase

    - name: Apply stash
      run: |
        git stash pop

    - name: Deploy to GitHub Pages
      run: |
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin main 
